language: python
services:
  - postgresql
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE sde;" -U postgres
script:
  - py.test -v --cov esy --cov-report term-missing tests --cov-config=.coveragerc-travis
after_success:
  - coveralls
